### ISSUE TITLE
Should this ZenPack work with Zenoss 5.1?

### ISSUE THREAD

**Issue by r2ewj** [linkslice/ZenPacks.community.HAProxy#3]
I was able to install the Zenpack fine, however I get the error below when I try to use one of the modeler plugins.

I have version 1.8.1 of the PythonCollector zenpack installed. Any ideas?

Thanks!

2017-02-27 22:11:01,364 INFO zen.ZenModeler: Connecting to localhost:8789
2017-02-27 22:11:01,377 INFO zen.ZenModeler: Connected to the zenhub/0 instance
2017-02-27 22:11:01,403 ERROR zen.ZenModeler: Error occured: [Failure instance: Traceback (failure with no frames): <class 'Products.ZenHub.PBDaemon.RemoteException'>: : Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenHub/PBDaemon.py", line 101, in inner
    return callable(*args, **kw)
  File "/opt/zenoss/Products/ZenHub/services/ThresholdMixin.py", line 23, in remote_getThresholdClasses
    classes += pack.getThresholdClasses()
  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 878, in getThresholdClasses
    return self._getClassesByPath('thresholds')
  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 861, in _getClassesByPath
    for path, dirs, files in os.walk(self.path(name)):
  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 951, in path
    module = self.getModule()
  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 1150, in getModule
    _, packEntry = self.getEntryPoint()
  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 1133, in getEntryPoint
    dist = self.getDistribution()
  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 1123, in getDistribution
    return pkg_resources.get_distribution(self.id)
  File "/opt/zenoss/lib/python2.7/site-packages/pkg_resources.py", line 371, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/opt/zenoss/lib/python2.7/site-packages/pkg_resources.py", line 243, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/zenoss/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/zenoss/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: ZenPacks.community.HAProxy

]

**Comment by linkslice** [comment]
I honestly don't know. I've never had access to zenoss 5 and have never tested it. It would appear not! I'll take a look at this. I'm actually working on getting a zenoss 5 test cluster up and running right now. So I can hopefully test this more in the next week or so.

**Comment by r2ewj** [comment]
okay awesome, let me know if you would like me to test anything or if I can help in any other way.

Thanks!

Eric

**Comment by linkslice** [comment]
Sorry for the delay. I've finally gotten around to testing this, and it installs fine in my instance. Are you still having issues?

**Comment by r2ewj** [comment]
no problem, I actually resisted this a few weeks ago.  After removing the ZenPack and re-installing it I was able to get it work fine.  So something else in our Zenoss install must of been in a bad state. Thanks!

**Comment by linkslice** [comment]
Are you able to send a couple screenshots I could post here? Feel free to obfuscate sensitive information. I no longer have access to an environment running HA Proxy.
